### PR TITLE
#52

### PR DESCRIPTION
**Pull request by Anvarxon**
1. Added file of configuration and service.
2. Fixed a solution integration problem.
3. Could not get message to Telegram bot.
**Getting an error while trying to make POST request in Telegram API, that says "The JSON value could not be converted to Telegram.Bot.Types.Message.", which I can not solved, yet.**

Need help for bugfixing (@khamza85 @apfpo).

### CODE REVIEW

**Comment by Anvarxon** [comment]
Reminder: ngrok gives only one time URL per ngrok session. Which is received by ngrok http `{port number}`

**Review by khamza85 — CHANGES_REQUESTED** [review]
@Anvarxon , for testing purpose, can this Api echo whatever message comes from telegram bot? For instance if we get `{message}`, then return `echo {message}`

**Review by khamza85 — CHANGES_REQUESTED** [review]
@SandroShera created azure deployment for `TelegramApi` at https://exadelsandbox-officebooking-telegramapi-dev.azurewebsites.net/swagger.

- Make sure the app is startable. Currently it is failing to start (debug locally)
- Point the telegram bot to this new API URL , instead of `ngrok`

**Review by khamza85 — APPROVED** [review]

**Comment by khamza85** [comment]
Add more reviewers to pass the check.

**Review by Bazilis — APPROVED** [review]

**Review by SandroShera — APPROVED** [review]

**Pull request merged**
